name: Provision moodle infrastructure to dev environment

on: 
  push:
    branches:
    - develop
    - feature

jobs:
  build:
    name: build dev environment 
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ap-southeast-2
    - name: sync cloudformation templates to s3 bucket `moodle-stack-templates-home`
      run: |
        aws s3 sync templates s3://moodle-stack-templates-home --delete
    - name: Create moodle vpc stack if not exists, update stack if exists 
      env:
        stackName: moodle-vpc-stack-dev
        stackTemplateUrl: "http://moodle-stack-templates-home.s3.amazonaws.com/moodle-vpc-stack.yml"
        env: dev
      run: |
        ./.github/bin/moodle-vpc-stack-exists.sh
    - name: Create moodle rds stack if not exists, update stack if exists 
      env:
        stackName: moodle-rds-stack-dev
        stackTemplateUrl: "http://moodle-stack-templates-home.s3.amazonaws.com/moodle-rds-stack.yml"
        env: dev
        VpcStackName: moodle-vpc-stack-dev
        DatabaseUsername: ${{ secrets.AWS_AURORA_ROOT_USERNAME }}
        DatabasePassword: ${{ secrets.AWS_AURORA_ROOT_PASSWORD }}
      run: |
        ./.github/bin/moodle-rds-stack-exists.sh
    - name: Create moodle core stack if not exists, update stack if exists 
      env:
        stackName: moodle-core-stack-dev
        stackTemplateUrl: "http://moodle-stack-templates-home.s3.amazonaws.com/moodle-core-stack.yml"
        env: dev
        VpcStackName: moodle-vpc-stack-dev
      run: |
        ./.github/bin/moodle-core-stack-exists.sh